### ISSUE TITLE
Gettings tons of errors when trying to build the app screenshot of the log below

### ISSUE THREAD

**Issue by sakutty** [lkashl/WTH#2] opened 2021-04-09 18:27 UTC
![2021-04-09_21-25](https://user-images.githubusercontent.com/69316447/114224880-51101380-997a-11eb-9b37-65d6f155bd01.png)
I have tried to reinstall nodejs and npm to no avail

**Comment by 4nt11** [comment] 2021-04-09 18:48
Hey. Could you post the output of uname -a ? Also, it would be helpful if you say on which distro are you on atm.

**Comment by sakutty** [comment] 2021-04-09 22:41
> Hey. Could you post the output of uname -a ? Also, it would be helpful if you say on which distro are you on atm.

Linux linux 5.11.10-051110-generic #202103251032 SMP Thu Mar 25 10:35:48 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by sakutty** [comment] 2021-04-10 19:34
> > Hey. Could you post the output of uname -a ? Also, it would be helpful if you say on which distro are you on atm.
> 
> Linux linux 5.11.10-051110-generic #202103251032 SMP Thu Mar 25 10:35:48 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

I'm using Linux Mint it probably didn't say it because i upgraded my kernel and it must've changed

**Comment by 4nt11** [comment] 2021-04-10 20:29
> > > Hey. Could you post the output of uname -a ? Also, it would be helpful if you say on which distro are you on atm.
> > 
> > Linux linux 5.11.10-051110-generic #202103251032 SMP Thu Mar 25 10:35:48 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
> 
> I'm using Linux Mint it probably didn't say it because i upgraded my kernel and it must've changed

How weird... I would've said that you were on some not-Debian based distro, but you're on Mint...
You followed correctly the npm installation steps? This might be part of the problem. 
Good luck!

**Comment by sakutty** [comment] 2021-04-10 21:25
> > > > Hey. Could you post the output of uname -a ? Also, it would be helpful if you say on which distro are you on atm.
> > > 
> > > 
> > > Linux linux 5.11.10-051110-generic #202103251032 SMP Thu Mar 25 10:35:48 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
> > 
> > 
> > I'm using Linux Mint it probably didn't say it because i upgraded my kernel and it must've changed
> 
> How weird... I would've said that you were on some not-Debian based distro, but you're on Mint...
> You followed correctly the npm installation steps? This might be part of the problem.
> Good luck!

I dont think its a problem with npm the logs said so too and i reinstalled it too ill try installing it another way it may work for now i will try installing it on my GUI WSL2 Ubuntu vm

**Comment by sakutty** [comment] 2021-04-10 21:45
> > > > Hey. Could you post the output of uname -a ? Also, it would be helpful if you say on which distro are you on atm.
> > > 
> > > 
> > > Linux linux 5.11.10-051110-generic #202103251032 SMP Thu Mar 25 10:35:48 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
> > 
> > 
> > I'm using Linux Mint it probably didn't say it because i upgraded my kernel and it must've changed
> 
> How weird... I would've said that you were on some not-Debian based distro, but you're on Mint...
> You followed correctly the npm installation steps? This might be part of the problem.
> Good luck!

![image](https://user-images.githubusercontent.com/69316447/114285350-2055da00-9a5f-11eb-88db-1ca41a10e240.png)
 Yeah it was a problem with npm i had installed it with sudo apt install npm && sudo apt install nodejs but that messed it up somehow i installed it with :
**curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
sudo apt-get install -y nodejs**
...and now it works. Thanks for the help!

**Comment by 4nt11** [comment] 2021-04-11 06:53
Glad that it worked out! Good luck my friend!!

**Comment by sakutty** [comment] 2021-04-12 18:02
Okay so i tested it on my linux machine and im getting a error but it runs what did i do wrong?
![2021-04-12_21-01](https://user-images.githubusercontent.com/69316447/114440080-654e4d80-9bd2-11eb-94a7-535161223f2e.png)

**Comment by 4nt11** [comment] 2021-04-12 21:36
I had a similar problem, but I'm not on a Debian/Ubuntu-based distro. Which one are you on? If I had to guess, I think you're on Garuda Linux right now. But still, I'll need to know on which distro you are on rn. Good luck!

**Comment by sakutty** [comment] 2021-04-12 22:09
> I had a similar problem, but I'm not on a Debian/Ubuntu-based distro. Which one are you on? If I had to guess, I think you're on Garuda Linux right now. But still, I'll need to know on which distro you are on rn. Good luck!

I think i said so already but im on Mint right now.
Garuda doesnt work for me lol

**Comment by 4nt11** [comment] 2021-04-13 01:29
> I think i said so already but im on Mint right now.

Yes, you said that. But before you were on WSL, but now apperently not. If you are on WSL, the installation process _may_ be different. I'm not the dev, but the fact you're using WSL _might_ be the problem.

**Comment by sakutty** [comment] 2021-04-13 21:08
> > I think i said so already but im on Mint right now.
> 
> Yes, you said that. But before you were on WSL, but now apperently not. If you are on WSL, the installation process _may_ be different. I'm not the dev, but the fact you're using WSL _might_ be the problem.

Nope i was on WSL and it was working on Linux Mint (i am dualbooting) it does not work even though i used the same commands

**Comment by lkashl** [comment] 2021-04-13 21:52
@ssepi0l-pv thanks very much for helping out with the issues! :)

@sakutty, this is looking like a dupe of https://github.com/lkashl/WTH/issues/1 to me. TLDR: It should be fixed if you do a git pull, if that's not the case though feel free to get back to me

The tools been made to fail in modules rather than as a whole so only stats specific to a problem are usually impacted

Also, does your CPU usage always show up as 0?

**Comment by sakutty** [comment] 2021-04-15 13:04
> @ssepi0l-pv thanks very much for helping out with the issues! :)
> 
> @sakutty, this is looking like a dupe of #1 to me. TLDR: It should be fixed if you do a git pull, if that's not the case though feel free to get back to me
> 
> The tools been made to fail in modules rather than as a whole so only stats specific to a problem are usually impacted
> 
> Also, does your CPU usage always show up as 0?

I installed Ubuntu 21.04 today and installed KDE on it hopefully it will work for now i will restore everything I had from mint i will get back to you later and post if it will work

**Comment by lkashl** [comment] 2021-04-25 13:48
Hey guys,

Since there hasn't been any activity on this one for over a week I'll close it out for now. Feel free to reopen the ticket in case there are any further issues.

Thanks,
Kash

**Closed as completed** 2021-04-25 13:49 UTC
